# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29209da6caa4cc372be0d1d97fc7e940b5fc0d7143fe855c624028c4eeeea8c086d062287b73cf6813ecb9277277ef85db21a368f7a00d78fbba118739391350

test:
  secret_key_base: 256785ad6bcd6af1056bb25443675bd392444053b069763d17cc5b6f1b78879ae8e628a1abd69c7c3a59f338aa2d51fbcc4d6a06f8beb7c590434db57f44697c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
